name: prettier
on: [push, pull_request]
jobs:
  prettier:
    name: Prettier Style-Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"
      - name: Install Prettier
        run: npm install --save-dev --save-exact prettier
      - name: Run Prettier
        run: npx prettier --check .
